### ISSUE TITLE
Error: Sprockets::Rails::Helper::AssetNotFound in Railsui::Page#index [solved]

### ISSUE THREAD

**Issue by DogAndCode** [getrailsui/railsui#10]
After run` bin/dev` I selected the theme for the UI that we can select and the installation started I receive this error:

```
_Sprockets::Rails::Helper::AssetNotFound in Railsui::Page#index_

    else
          message =  "The asset #{ path.inspect } is not present in the asset pipeline.\n"
          raise AssetNotFound, message unless unknown_asset_fallback

          if respond_to?(:public_compute_asset_path)
            message << "Falling back to an asset that may be in the public folder.\n"
```

Then I closed and restarted with `bin/dev`

**Comment by DogAndCode** [comment]
Solved doing this: [](https://stackoverflow.com/questions/70482086/rails-7-0-esbuild-running-app-gives-error-command-build-not-found)

1.- Add script (see below) to package.json
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    ...
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css"
  }
}
2.- yarn build
3.- yarn build:css

And after that adding this to manifest.js
//= link application.css

**Comment by justalever** [comment]
> Solved doing this: https://stackoverflow.com/questions/70482086/rails-7-0-esbuild-running-app-gives-error-command-build-not-found
> 
> 1.- Add script (see below) to package.json
> 
> ```
> {
>   "name": "app",
>   "private": "true",
>   "dependencies": {
>     "@hotwired/stimulus": "^3.0.1",
>     ...
>   },
>   "scripts": {
>     "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
>     "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css"
>   }
> }
> ```
> 
> 2.- `yarn build` 3.-` yarn build:css`
> 
> After that adding this to manifest.js `//= link application.css`

This normal is an additional step that gets configured after successfully installing a theme. Tailwind in particular would resemble what you have here so somehow this got out of sync. I can't quite reproduce this at the moment. 🤔
