### ISSUE TITLE
Quick typo fix and wrong link

### ISSUE THREAD

**Issue by zzJZzz** [getrailsui/railsui#14]
https://railsui.com/docs/design_system

Origins
When we create new themes most design systems -------> Should this be "are" a created first. To develop atomic patterns, we use this exercise to be more efficient in an application with many views. In the software world, you can think of this as practicing the D.R.Y. (don't repeat yourself) principle.

The bottom right navigation link appears it should link to "Interaction" instead of "Updates"

**Comment by justalever** [comment]
Thanks for spotting!
