### ISSUE TITLE
undefined method `safe_load_file' for Psych:Module

### ISSUE THREAD

**Issue by manuchap** [getrailsui/railsui#16]
Install went fine but the app crashed after selecting Bootstrap or Tailwind with this error.

**Comment by justalever** [comment]
Hoping the [latest commit](https://github.com/getrailsui/railsui/commit/2282110c551a3424e4c866e969a82227128818c9) solves this issue. You'll want to update the gem `bundle update railsui`. Then run `bundle`. If that doesn't work I'd recommend a fresh app and install. Sorry for the delay!
