### ISSUE TITLE
Honoring the scaffold files in the project

### ISSUE THREAD

**Issue by joshmvandercom** [getrailsui/railsui#33]
When you install it does add the scaffold files to `/lib/templates/erb/scaffold/*.erb.tt`. But if you update them it still uses the templates from within the rails ui gem.

Curious if this was as a design system to support updates?

Perhaps it makes sense to have a configuration option is to allow you to select between the engine and local for the scaffold?

**Comment by justalever** [comment]
@joshmvandercom, thanks for this! To clarify, you modified the included scaffold templates, but is it still using the Rails UI defaults? 

If you want to disable those from continuously leveraging Rails UI  you can head to your `config/application.rb` file and comment or remove this line. Assuming you have templates copied over, the changes you make to them should be reflected now 👍 

```ruby
# config/application.rb
g.template_engine :railsui`
```

**Comment by joshmvandercom** [comment]
Ok @justalever I wasn't sure if turning that off would affect other things. But yes removing that line allows me to customize the scaffold.

I guess I might lose the link being placed into the nav, but I don't think that is an issue.
