### ISSUE TITLE
Why does install generator include Devise and a User model?

### ISSUE THREAD

**Issue by petealbertson** [getrailsui/railsui#35]
I just tried setting up Rails UI for the first time and was super intrigued by the project. But I'm curious why the install generator offers no ability to customize what's installed? In particular, I'm concerned about the obligatory inclusion of Devise along with a User model, something my app currently doesn't have or need. At the very least I would expect some documentation that includes at least _some_ detail on what running install includes.

I know issues that just complain about decisions aren't great, which is why I originally intended to PR changes that would have the install generator ask the user if they want a User model or Devise, but looking at `setup.rb`, Devise appears to be very tightly woven into various aspects if this repo, so adding such flexibility felt like a lot of extra effort to make work.

At the very least, the site's documentation and repo README should warn developers about the obligatory inclusion of Devise, and that the install generator will change and migrate your DB by default.

**Comment by justalever** [comment]
Thanks for the feedback @petealbertson!

If you look at the README FAQ section, there's a section "What happens during installation?" that outlines the gist of everything. 

We weave devise views into a typical template when installing one with Rails UI. Those views are customized based on Devise at this time but there is a future where I can see being able to choose to either opt out of generating a User model or have a different auth solution with pre-designed templates installed.

Do you want to have the User model generated by default or prefer something other than Devise?

**Comment by petealbertson** [comment]
I missed the details in the README, but fwiw, your website docs do not have the same detail with regard to installation. All I saw was `Additionally, it installs and configures a couple other handy gems Rails UI leverages inside most views.`

Regardless, this is a UI tool so there is no logic to including models and migrations (let alone a very opinionated user auth gem) in the install generator. UI tools by definition should not include anything beyond front-end HTML/CSS/JS. Otherwise, you're not "RailsUI" but "Rails UI and User Auth". I would never choose a UI tool that makes those DB or model decisions on my behalf, so even an opt-in experience is questionable to me.

**Comment by justalever** [comment]
@petealbertson got it! Thanks for the feedback. The goal with auth-included is to solve the repeatable task of designing authentication views. I totally get it's not going to appeal to everyone.
