### ISSUE TITLE
Issue with missing partials in railsui on Rails 7.2

### ISSUE THREAD

**Issue by fabianoleittes** [getrailsui/railsui#38]
Hi @justalever ,

I hope you're doing well.

First off, congratulations on the incredible work you're doing with Railsui, it's a fantastic tool!

I've been testing Railsui with a fresh Rails 7.2 app and have encountered an issue. Some partials that should be copied to `views/shared` aren't included. Specifically, I'm missing the following:

- `shared/fonts`
- `shared/meta`
- `custom_color_css`
- `shared/flash`

I'm looking into it on my end but wanted to bring this to your attention in case it's something you've seen before or might want to investigate.

P.S.: The installation process was seamless, with no issues whatsoever.

Thanks for all your hard work!

![Screen Shot 2024-08-14 at 18 07 57](https://github.com/user-attachments/assets/24a177c3-b091-45b3-ae4d-53f5a6a47c80)
![Screen Shot 2024-08-14 at 18 08 50](https://github.com/user-attachments/assets/e1bc44c0-eddc-4e3e-82b8-9b443e19133e)
![Screen Shot 2024-08-14 at 18 10 25](https://github.com/user-attachments/assets/a50f656b-2a68-483c-b0e8-5b12cecbfb11)
![Screen Shot 2024-08-14 at 18 10 37](https://github.com/user-attachments/assets/e00e202b-d267-460d-80f9-9c4bdc696b50)

**Comment by justalever** [comment]
Hey @fabianoleittes! 

Thanks for the issue. I upgraded to 7.2 on my end and tried fresh installs for both templates, but I can't quite reproduce what you're facing here. I am, however, also running Ruby 3.3.3. It appears you're on an older version. I don't know if upgrading would solve the problem, but it could be worth a shot. 

From the looks of it, the installation might have gotten hung up, and some files failed to copy. I can't pinpoint why.

**Comment by fabianoleittes** [comment]
Hey @justalever ,

Thanks for getting back to me—I appreciate it. I updated my Ruby version to 3.3.4 and created a fresh Rails app, but unfortunately, the same issue persists.

Thanks again for your help.

**Comment by justalever** [comment]
Interesting! Do you happen to spot any errors in your logs during install? There could be a step being skipped based on system dependencies.

**Comment by fabianoleittes** [comment]
It sounds like things went smoothly during the installations, I didn't see any errors!

**Comment by troyizzle** [comment]
I ran into this  issue using same the rails and ruby version when using this command to set up my rails app.
`rails new app --database=postgresql --css=tailwind`

I did notice this in the logs
```
22:11:41 web.1  | error Command "build:css" not found.
22:11:41 web.1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I ended up just recreating the app without --css flag and everything worked!
`rails new app --database=postgresql`

**Comment by justalever** [comment]
Sorry about this! I'm aware of the issue. Passing any CSS flags might throw a wrench when installing the current version at the moment. To make this more standardized and predictable, v3 will require passing a CSS flag for tailwind which should make things more consistent.
