### ISSUE TITLE
railsui-f3cb2a2690c2 is broken on Rails 8 (stimulus.rake) - Don't know how to build task 'update'

### ISSUE THREAD

**Issue by parolkar** [getrailsui/railsui#44]
Hi There, 
   I hit this problem while using railsui on latest Rails 8.0.0

<pre>
user@P6R-MBP rails8_ui % rails railsui:install
bin/rails aborted!
Don't know how to build task 'update' (See the list of available tasks with `bin/rails --tasks`)
/vendor/bundle/ruby/3.3.0/bundler/gems**/railsui-f3cb2a2690c2/lib/tasks/stimulus.rake**:4:in `block (2 levels) in <main>'
/vendor/bundle/ruby/3.3.0/bundler/gems/railsui-f3cb2a2690c2/lib/tasks/stimulus.rake:2:in `block in <main>'
/vendor/bundle/ruby/3.3.0/bundler/gems/railsui-f3cb2a2690c2/lib/tasks/stimulus.rake:1:in `<main>'
/vendor/bundle/ruby/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:687:in `load'
/vendor/bundle/ruby/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:687:in `block in run_tasks_blocks'
/vendor/bundle/ruby/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:687:in `each'
/vendor/bundle/ruby/3.3.0/gems/railties-8.0.0/lib/rails/engine.rb:687:in `run_tasks_blocks'
/vendor/bundle/ruby/3.3.0/gems/railties-8.0.0/lib/rails/application.rb:558:in `block in run_tasks_blocks'
/vendor/bundle/ruby/3.3.0/gems/railties-8.0.0/lib/rails/engine/railties.rb:15:in `each'
/vendor/bundle/ruby/3.3.0/gems/railties-
.
.
.
(See full trace by running task with --trace)
</pre>

My Gemfile:
<pre>
--------
source "https://rubygems.org"

ruby '3.3.0'

gem "railsui", github: "getrailsui/railsui", branch: "main"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.0"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem "jsbundling-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem "cssbundling-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end

----------
</pre>

**Comment by justalever** [comment]
Hey @parolkar, can you try moving the `gem "railsui", github: "getrailsui/railsui", branch: "main"` line down to the bottom of the file and running bundle install. After that, try the installer again and see if you are successful.
